# The URL the site will be built for
base_url = "https://slnq.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

title = "夏果"

generate_feeds = true

# set taxonomies vaild
taxonomies = [
  { name = "categories", feed = true },
  { name = "tags", feed = true },
  { name = "links", feed = false }
]

# When set to "true", the generated HTML files are minified.
minify_html = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false
hard_line_breaks = true

[extra]
# Put all your custom variables here
files = []
format = []
